name: Build
on: push
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 18
            - name: Full build
              run: |
                  npm ci
                  npm run build
                  npm run test
                  npm run lint
            - name: Release info
              run: npx standard-version --dry-run
